juju/charm-tools

.gitignore
.travis.yml
Makefile
README.md
tox.ini

Add support for Travis CI to leverage existing tox setup

Travis CI support

---

charmtools/fetchers.py

Handle empty metadata.yaml

---

charmtools/compose/fetchers.py
charmtools/fetchers.py

Move LPGitFetcher upstream and add missing call to rename()

---

README.md
charmtools/charms.py
tests/trusty/mysql/hooks/charmhelpers/fetch/__init__.py

Addressing the charm-tools readme issue #18

Readme update

---

charmtools/charms.py
tests/trusty/mysql/hooks/charmhelpers/fetch/__init__.py

Addressing issue #22
Even though I didn't change any code, `make test` ran successfully on my machine.

Replacing "sould" with "should".

---

charmtools/build/__init__.py
charmtools/build/fetchers.py
charmtools/build/tactics.py

Very simple metrics collection around which layers and interfaces are used. The intention is to support visualization down the road.

enable simple metics collections to help visualize charm ecosystem

---

charmtools/build/tactics.py

Make sure wheel is available in build venv

---

charmtools/build/tactics.py

update the URL that gets shoved into the generated hooks.

correct doc URL in generated hooks

---

charmtools/build/tactics.py

These are blockers for the big data layered charms.

Add dist.yaml and resources.yaml as merged YAML files

---

charmtools/build/__init__.py
tests/test_build.py

Also fixes:
* Fix #11
* Fix #19
* Fix #33
* Fix #106

Fixed #83: Clean up files removed in base layers

---

charmtools/create.py
charmtools/templates/reactive_bash/__init__.py
charmtools/templates/reactive_bash/template.py
charmtools/templates/reactive_python/__init__.py
charmtools/templates/reactive_python/template.py
setup.py

Set reactive-python to the default

Fixed #77: Added templates for reactive charms

---

charmtools/build/tactics.py

Fix #118: TypeError when processing some Yaml files during charm build

---

charmtools/pullsource.py

Download dir will be the name of the cloned repo. Rename it
to match the name of the layer or interface. Fixes #130.

Rename downloaded layer/interface dir

---

charmtools/build/__init__.py

Avoid multiple fetches of a layer or interface during charm-build.

---

charmtools/charms.py
tests/test_charm_proof.py

Validate 'series' in metadata.yaml. Fixes #143.

---

charmtools/charms.py
tests/test_charm_proof.py

Add min-juju-version support to charm-proof. Fixes #141.

---

charmtools/charms.py
tests/test_charm_proof.py

validate payloads in metadata

---

charmtools/bundles.py

Fix possible KeyError when proofing bundle.

---

charmtools/repofinder.py
tests/test_repofinder.py

Add push/submit branches to repo finder. Fixes #155.

---

charmtools/build/__init__.py
charmtools/build/fetchers.py

Add --no-local-layers option to charm-build. Fixes #149.

---

charmtools/charms.py
tests/test_charm_proof.py

This is a first pass at linting actions. We need to do a full lint of the jsonschema to call this complete. However, this will verify the YAML parses, that there are no juju-* actions, and that the action file exists and is executable.
Fixes #91 #161

lint actions.yaml

---

charmtools/version.py

Better version command handling

---

charmtools/charms.py
tests/test_charm_proof.py

actions_yaml_file

---

charmtools/build/__init__.py
charmtools/build/errors.py
charmtools/build/tactics.py
tests/test_build.py
tests/trusty/invalid-layer/README.md
tests/trusty/invalid-layer/layer.yaml
tests/trusty/invalid-layer/metadata.yaml

I found a usability error when using charm-build so I also took the time to fix the problem. Thanks to @johnsca for his help on how to import BuildError properly.

Yaml error

---

charmtools/build/__init__.py

This runs a proof immediately after a successful build, addressing issue #171

Run `charm proof` immediately after `charm build`

---

charmtools/bundles.py
charmtools/proof.py
charmtools/utils.py

Add a check for bundle.yaml, if juju version is 2.0 or higher

Catch bundles.yaml -> bundle.yaml

---

charmtools/repofinder.py

stderr to devnull for repo detection

---

setup.py

paramiko less than 2.0 (fixes #199)

---

requirements.txt
setup.py

Fixes #246 because deps in python are hard

lock secretstorage because launchpadlib didn't fixes #246

---

charmtools/build/builder.py
tox.ini

Indicate when local layers were used and from where

---

charmtools/build/tactics.py

Create directory, regardless of entity

---

charmtools/build/config.py

fixes #289 
```
(py27) marco@T430:~/temp/charm-tempest/src$ charm-build -l DEBUG
build: Composing into /home/marco/temp
build: Destination charm directory: /home/marco/temp/builds/tempest
build: {
"INTERFACE_PATH": null, 
"JUJU_REPOSITORY": "/home/marco/temp", 
"LAYER_PATH": "/home/marco/temp", 
"_charm": ".", 
"_charm_metadata": {
"description": "Tempest is a set of integration tests to be run against a live Openstack\ncluster. Tempest has batteries of tests for Openstack API validation,\nscenarios, and other specific tests useful in validating an Openstack\ndeployment.\n", 
"maintainer": "Liam young <liam.young@canonical.com>", 
"name": "tempest", 
"requires": {
"dashboard": {
"interface": "http"
}, 
"identity-admin": {
"interface": "keystone-admin"
}
}, 
"series": [
"xenial", …
```

Removing trailing slashes to prevent empty directory creation (fixes #289)

---

charmtools/build/tactics.py
charmtools/utils.py
tests/test_build.py
tests/trusty/mysql/metadata.yaml
tests/trusty/tester/metadata.yaml

This de-duplicates metadata series and fixes #297

Remove duplicates from series field in metadata tactic fixes #297

---

requirements.txt
setup.py

Fixes stacktrace on charm create fixes #287

Increase deps fixes #287

---

charmtools/build/builder.py
charmtools/build/fetchers.py
tests/test_build.py

This resolves #324 by moving the layer index to https://github.com/juju/layer-index

Migrate layer index to GitHub repo

---

charmtools/build/builder.py
charmtools/build/fetchers.py

Remove pront from #341, replace with debug log messages
Show source of local interfaces like we do with layers

charm-build output fixes

---

charmtools/build/builder.py

Strip "screen." prefix from TERM

---

charmtools/build/builder.py
charmtools/version.py
tests/test_build.py

Fix metrics by moving to GA

---

charmtools/git_version.py

Docs didn't mention character restrictions, but I found https://github.com/snapcore/snapcraft/blob/master/schema/snapcraft.yaml#L52

Fix version long form to work with snapcraft

---

charmtools/git_version.py

When I tested the version handling previously, I didn't realize that it was picking up the version from the current directory rather than from the snap or Python package.  When run from another directory, it didn't
work in either the snap or Python package.
Fixes #362

Fix "unable to determine version"

---

README.rst

Congratulations on the snap of charm-tools. Here's a badge to show the latest build status.

Add a snapcraft build badge

---

charmtools/build/builder.py

Small error message change to clarify the error. I just ran into the "Changed file owned by another layer" error and was confused as to what it meant.

updating some error messages to hopefully clarify them

---

charmtools/build/builder.py
charmtools/generators/generator.py
charmtools/proof.py
charmtools/pullsource.py

Add confinement checks for proof, pull-source, and layers.  Also make the other errors more consistent.
Fixes #371

More snap confinement error messages

---

snap/snapcraft.yaml

Add plan management commands from github.com/juju/plans-client to the snap.

Add github.com/juju/plans-client commands.

---

charmtools/build/builder.py
charmtools/build/tactics.py

When an override is provided and previous versions were in the wheelhouse, the older versions being removed would still be signed and thus cause fatal errors the next time the build was run.
This also includes improvements to the error messaging around home directory checking.

Fix signing when duplicate wheel is purged

---

charmtools/build/builder.py
charmtools/build/config.py
charmtools/build/tactics.py
tests/test_build.py

Fix tactics defined in a layer not applying to that layer

---

charmtools/build/builder.py
charmtools/build/tactics.py
tests/test_build.py
tests/trusty/mysql/hooks/start
tests/trusty/mysql/hooks/stop

Make standard hooks generated from template

---

charmtools/pullsource.py

Fix imports in pullsource for Python 3

---

charmtools/templates/python/template.py
charmtools/templates/python_services/template.py
charmtools/templates/reactive_bash/template.py
charmtools/templates/reactive_python/template.py

Add Py3 workaround to missed charm templates

---

charmtools/build/builder.py

Handle invalid charm names gracefully

---

helpers/snap-wrappers/charm
snap/snapcraft.yaml

Fixes #415
Process for merging this would be to merge #432 first, update the version for release, let it build and get to edge, then promote it to at least beta, all before merging this to master.
Note: This PR is currently against #432 rather than master so that the diff works out properly.

Switch to classic confinement

---

charmtools/build/builder.py
charmtools/generators/generator.py
charmtools/proof.py
charmtools/pullsource.py
charmtools/utils.py
tests/test_charm_create.py
tests/test_utils.py

These are no longer needed with the classically confined snap.
Fixes #450

Remove checks for home directory

---

charmtools/charms.py
tests/test_charm_proof.py

Fix proof extensions failing with empty-string missing values

---

charmtools/build/builder.py

Handle errors better when detecting the `TERM` type for `charm-build`.
Also add a `--force-color` option for `charm-build` and rename `--force-raw` for `charm-inspect`
Fixes #472

Improve error handling in TERM detection

---

charmtools/build/tactics.py
tests/test_build.py

Updated version of #469 
Fixes #468

Fix error handling in py2 for missing VCS

---

charmtools/build/tactics.py

Improve docs for LayerYAML tactic

---

charmtools/build/inspector.py

Fix charm-layer handling of old format build-manifest

---

charmtools/charms.py
tests/test_charm_proof.py

Make series required

---

setup.py

Resolve vergit python package dependency

---

charmtools/charms.py
tests/test_charm_proof.py

Move daemonset to deployment.type;

---

charmtools/charms.py
tests/test_charm_proof.py

Change deployment.type optional;

---

charmtools/charms.py
tests/test_charm_proof.py

Add functions support;

---

charmtools/templates/operator_python/__init__.py
charmtools/templates/operator_python/template.py
setup.py

Adds a basic template charm for Operator charms
Did not add specific code coverage for this template, as none of the specific templates

Add Operator charm template

---

charmtools/build/tactics.py
tests/layers/whbase/wheelhouse.txt
tests/layers/whlayer/wheelhouse.txt
tests/test_build.py

The previous fix for #571 regressed handling of comments.
Fixes #573

Fix handling of comments in wheelhouse

---

charmtools/pullsource.py

Addendum to [lp:1893081](https://bugs.launchpad.net/charmed-kubernetes-testing/+bug/1893081)

Add revision info to output of pull-source

---

snap/snapcraft.yaml

fix snap build for updated charmstore-client

---

.github/workflows/tox.yaml
.travis.yml
charmtools/build/tactics.py

Copy the hook template in for -relation-created hooks so that they are handled by the charm.
Also switch to GitHub Actions instead of Travis for tests.

Add support for -relation-created hook

---

.github/ISSUE_TEMPLATE.md
docs/changelog.rst
docs/commands.rst
docs/conf.py
docs/contributing.rst
docs/index.rst

Please review/merge commit by commit

Remove mentions of charm store commands from docs and create changelog for v3.0.0 release

---

charmtools/build/builder.py

The bare minimum of build packages may be missing following commit 2482f0f and commit 725d2cb.
While the resolution may belong in charmcraft, we need a workaround.
Fixes #638

Add workaround for missing build packages

---

charmtools/create.py
helpers/snap-wrappers/charm
snap/snapcraft.yaml

Please review commit by commit.

Add missing stage-package for git on bionic and deprecate the `charm create` command
