- charmtools/build/__init__.py
- charmtools/build/fetchers.py
```
$ charm build
build: Composing into /home/johnsca/juju/envs/dev
build: Unable to locate layer:dummy. Do you need to set LAYER_PATH?
```
> Fix #56: Catch and report missing layers and interfaces

- charmtools/build/tactics.py
- tests/test_build.py
Apparently, I completely misunderstood the point of the `--no-binary` option for `pip wheel`.  It actually controls what `pip` pulls down from pypi.python.org and not what gets generated in the wheelhouse.  I've been told that wheels are inherently binary, pre-compiled, and platform specific.
But it seems that using `pip install --download wheelhouse/ --no-binary :all:` instead of `pip wheel -w wheelhouse/ --no-binary :all:` gets us what we want.  Technically, the result is no longer a wheelhouse, since it contains (only) sdists, so I'd be ok with changing the name to "pydeps" and "pydeps.txt" or similar, but for now I left it as "wheelhouse".
> Fix wheelhouse containing platform specific wheels

- charmtools/build/tactics.py
- tests/test_build.py
This depends on juju-solutions/reactive-base-layer#10.
> Use Python 3 for layered charms

- charmtools/build/tactics.py
This either needs to be handled here, or pip should simply be defined in the "base" layer and L624 can just be removed
> pip 8.0.0 wreaks havoc. lock it to 7.X

- charmtools/build/tactics.py
- tests/test_build.py
- tests/trusty/mysql/config.yaml
This pull forces all strings to use quotes so Juju does not try to read the yaml string 01182252 as an int.
Adding configuration and tests so this does not revert in the future.
I also had to fix a hash on metadata.yaml in the tests, don't know what that was about other than the test was failing when I found it.
> Addresses issue 99 where Juju has a problem with strings starting with zero

- charmtools/build/__init__.py
- charmtools/fetchers.py
```
build: Composing into /home/ubuntu/t
build: Unable to run "git": No such file or directory
```
> Fixed #102: Report useful error message when fetch fails due to missing VCS tool

- charmtools/build/__init__.py
- charmtools/build/tactics.py
```
build: Composing into /home/johnsca/juju/envs/apache-dev
build: Processing layer: layer:basic
build: Processing layer: hadoop-client
build: Processing interface: hadoop-plugin
charmtools.build.tactics: Missing implementation for interface role: provides.py
```
> Fixed #105: Raise error if interface is missing implementation for role being used

- charmtools/build/tactics.py
- charmtools/utils.py
- tests/test_build.py
This PR is still in flight as I have not added tests for this change, but when testing using the given example by @marcoceppi here https://gist.github.com/marcoceppi/ad318d081e3b30857819
> Adjusted the deep merge operation to support merging of lists

- charmtools/build/__init__.py
- charmtools/fetchers.py
- charmtools/repofinder.py
- tests/test_build.py
- tests/test_fetchers.py
- tests/test_repofinder.py
Prints a WARN message if repo key is not present. If the top layer is in a vcs directory (git, bzr, or hg), will also provide a suggested repo url.
> During `charm build`, suggest a 'repo' key for layer.yaml (if missing)

- charmtools/build/fetchers.py
- charmtools/fetchers.py
- charmtools/pullsource.py
If the charm is layered, and has a repo key set in layer.yaml, the top layer will be cloned. Otherwise, the charm will be downloaded from the charm store (cloned from bzr if possible, else archive downloaded and extracted).
Examples to test with:
`charm-pull-source cs:~tvansteenburgh/trusty/django-test-1 # layered, with repo key in layer.yaml`
`charm-pull-source cs:~marcoceppi/trusty/ubucon # layered, no repo key in layer.yaml`
`charm-pull-source cs:~tvansteenburgh/meteor-test # not layered`
> Make pull-source clone the charm's top layer if possible

- charmtools/fetchers.py
- tests/test_fetchers.py
Lower match precedence than the site-specific Github and Launchpad fetchers. Will match any url that starts with "git" or ends with ".git".
> Add a generic git fetcher

- charmtools/build/fetchers.py
When the fetcher searches for local layers and interfaces, look
for a prefixed dir as well as a dir that matches the layer or
interface name exactly. A convenience for users who have cloned
conventionally-named layer/interface repos into their
LAYER_/INTERFACE_PATH. Fixes #116.
> Support layer- and interface- prefix for local layers

- charmtools/build/__init__.py
- tests/test_build.py
This option enables a post-build report detailing what files have changed, based on the signatures in the existing `.build.manifest`
> Add --show-report option to charm-build

- charmtools/build/__init__.py
- charmtools/cli.py
- charmtools/create.py
- charmtools/generate.py
- charmtools/proof.py
- charmtools/pullsource.py
- charmtools/test.py
- charmtools/utils.py
```
(.venv) 148 tvansteenburgh@xenial-vm:~/src/charm-tools⟫ charm help plugins
charm plugins
Plugins are implemented as stand-alone executable files somewhere in the user's PATH.
The executable command must be of the format charm-<plugin name>.
add          Add icon, readme, or tests to a charm
build        Build a charm from layers and interfaces
compose      compose has been deprecated, please use build
create       Create a new charm
help         Get help for a charm subcommand
layers       Inspect the layers of a built charm
proof        Perform static analysis on a charm or bundle
pull-source  Download the source code for a charm, layer, or interface
test         Execute charm functional tests
version      charm-tools 2.0a1
```
Fixes #137
> Make all plugins handle --description

- charmtools/bundles.py
- charmtools/charms.py
- charmtools/generate.py
- charmtools/get.py
- charmtools/info.py
- charmtools/proof.py
- requirements.txt
- setup.py
- tests/test_bundle_proof.py
- tests/test_charm_generate.py
- Removed all the remote proofing stuff. Now we just proof
locally with jujubundlelib, with some of our own checks
on top.
- Had to pin requests at 2.6.0 b/c theblues, a dep of
libcharmstore, requires that specific version.
- Integration tests ('make check') all pass.
Fixes #144.
> Replace charmworldlib with libcharmstore

- .gitignore
- charmtools/build/tactics.py
- charmtools/utils.py
Instead of raising a CalledProcessError, write the output of the failed
command, and the command itself, to stderr, then exit with the exit
code of the failed command.
Fixes #126.
> Better feedback to user when command fails

- charmtools/build/__init__.py
- If no series given on cmd line and charm is multi-series
('series' key in metadata.yaml), don't build in a series dir.
- If no series given on cmd line and charm is not multi-series,
build in default series dir.
- Added new log.info to show the final destination dir of the
built charm.
- 'charm_name' property and 'warnings' import removed b/c
not used anywhere.
Fixes #115.
> Don't build multi-series charms into a series dir

- charmtools/build/tactics.py
- tests/test_build.py
- tests/trusty/tester/layer.yaml
Ensure that options are only set for layers that are included.
This also ensures that one doesn't forget to nest the options under the
layer name.
Note: The `additionalProperties` is actually sufficient, but produces a
somewhat obscure error message.
> Validate layers for options (fixes #173)

- charmtools/build/tactics.py
This change pulls through an ignore specs in the ignore config file in
the interface.yaml file.
Fixes #192 interfaces.yaml ignore option doesn't have any effect
with charm build
> Enable interface.yaml ignore config option

- charmtools/utils.py
> Fix tactic loader

- charmtools/charms.py
- tests_functional/charms/unknown-metadata/metadata.yaml
- tests_functional/proof/expected/unknown-metadata
Adds integration tests for payloads key and adds payloads to the KNOWN_METADATA_KEYS list
> add payloads to metadata known keys fixes #196

- charmtools/build/builder.py
- tests/test_build.py
- tests/trusty/mysql/layer.yaml
- tests/trusty/test-base/config.yaml
Fixes #218 by ensuring that a layers deps are (recursively) appended to the list before itself.  This fixes a regression from 87c26dc4
> Fix the order of fetch vs append (fixes #218)

- charmtools/build/tactics.py
- charmtools/utils.py
- tests/test_build.py
- tests/trusty/mysql/metadata.yaml
- tests/trusty/tester/metadata.yaml
Also adding special case for 'maintainer' and 'maintainers' keys
in metadata.yaml where the only the top layer maintainers are
listed in the built artifact.
> Adding de-duplication for lists in metadata.yaml

- charmtools/templates/reactive_bash/template.py
- charmtools/templates/reactive_python/template.py
There's no need to do --recursive on these templates since there are no submodules present.
> --recursive isn't needed for these templates

- charmtools/build/builder.py
This changes the output from this:
```
build: Composing into /home/marco/Projects/silph.co
build: Destination charm directory: /home/marco/Projects/silph.co/trusty/silph-web
build: Please add a `repo` key to your layer.yaml, e.g. repo: git@bitbucket.org:marcoceppi/layer-thesilphroad.git
build: Processing layer: layer:basic
build: Processing layer: layer:nginx
build: Processing layer: layer:apt
build: Processing layer: layer:php-fpm
build: Processing layer: silph-web
build: Processing interface: http
build: Processing interface: php-fpm-stats
build: Processing interface: mysql
build: Processing interface: redis
proof: I: no hooks directory
proof: W: no copyright file
proof: W: README.md includes boilerplate: Step by step instructions on using the charm:
proof: W: README.md includes …
```
> proof the actual built charm

- charmtools/build/builder.py
- charmtools/build/tactics.py
- tests/test_build.py
Use actual layer name instead of directory name (fixes #254)
Also makes it fail fast on tactic lint failures instead of trying to proof the non-existent built charm (fixes #260).
> Use actual layer name instead of directory name

- charmtools/build/fetchers.py
- tests/test_build.py
Fixes #268 which causes any layer using bzr to collide with any other layer using bzr, with the result being that layers can be dropped, or the wrong code used entirely.
> Fix fetched bzr layer output directory collision

- charmtools/version.py
This makes it so everyone using charm-version from within a snap will actually get a result.
- [ X ] Are all your commits [logically] grouped and squashed appropriately?
- [ X ] Does your code pass `make test`?
> Snap version update

- charmtools/build/tactics.py
When includes: is defined, but None set to empty list (fixes #8)
> When includes: is defined, but None set to empty list (fixes #8)

- charmtools/templates/bash/files/hooks/relation-name-relation-broken
- charmtools/templates/bash/files/hooks/relation-name-relation-departed
- charmtools/templates/bash/files/hooks/relation-name-relation-joined
Shebang was not consistent in the same "bash" template.
[master]
```
$ head -n1 charmtools/templates/bash/files/hooks/*
==> charmtools/templates/bash/files/hooks/config-changed <==
#!/bin/bash
==> charmtools/templates/bash/files/hooks/install <==
#!/bin/bash
==> charmtools/templates/bash/files/hooks/relation-name-relation-broken <==
#!/bin/sh
==> charmtools/templates/bash/files/hooks/relation-name-relation-changed <==
#!/bin/bash
==> charmtools/templates/bash/files/hooks/relation-name-relation-departed <==
#!/bin/sh
==> charmtools/templates/bash/files/hooks/relation-name-relation-joined <==
#!/bin/sh
==> charmtools/templates/bash/files/hooks/start <==
#!/bin/bash
==> charmtools/templates/bash/files/hooks/stop <==
#!/bin/bash
==> …
```
> Use consistent shebang in the same template

- setup.py
argparse is part of the Python 2.7 stdlib.
> remove argparse from install_requires

- charmtools/build/builder.py
Stable JSON output for Issue #278
- [] Does this patch have code coverage?
Stable ordering is preferred as it makes diffs more readable and makes
it impossible to write flaky tests that rely on implicit ordering.
> Ensure JSON output has stable ordering

- requirements.txt
- setup.py
This fixes #274 by level-setting pip in setup.py and requirements.txt
> back down requirements for trusty pip (fixes #274)

- charmtools/build/tactics.py
- tests/test_build.py
Fixes #276
Also removes a deprecation warning by switching to `pip download` and
pins the pip version used in the venv to prevent unexpected major
version changes in the future.
> Actually activate the venv when building the wheelhouse

- charmtools/build/tactics.py
- tests/test_build.py
- tests/trusty/tester/layer.yaml
- tests/trusty/tester/layer/custom.py
- tests/trusty/tester/old_tactic
Existing custom tactics will break if written to the old signature.
Fixes #295
> Make Tactic.trigger signature backwards compatible

- charmtools/build/builder.py
- charmtools/build/config.py
- charmtools/build/fetchers.py
- charmtools/build/tactics.py
- charmtools/utils.py
- tests/test_build.py
path.path deprecated since 8.0 of path.py (commit a781071bf0fc9ff477b2d141baec343a7b3ab0e9). Use the correct path.Path.
> path is deprecated, use Path instead - LP#1660004.

- charmtools/build/builder.py
- charmtools/build/config.py
- charmtools/build/inspector.py
`charm build` on Ubuntu 17.04 throws a nasty warning because we use `yaml.load` instead of `yaml.safe_load`. This PR fixes that issue.
Output with warning:
```
build: Composing into /home/merlijn/PHD/tengu/tengu-charms/charms
build: Destination charm directory: /home/merlijn/PHD/tengu/tengu-charms/charms/builds/ssl-termination-proxy
py.warnings: /usr/lib/python2.7/dist-packages/charmtools/build/config.py:54: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:
import warnings
warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
In most other cases you should consider using 'safe_load(stream)'
data = …
```
> Use safe version of yaml.load

- charmtools/build/builder.py
- tests/test_build.py
To facilitate CI and testing of charms with new versions of Python dependencies, particularly those from base layers, you can now provide a wheelhouse.txt file via the `charm-build` CLI that will be applied
after all others which can thus override any dependencies from lower layers.
> Add option for wheelhouse overrides

- .github/ISSUE_TEMPLATE.md
Since we now only recommend using the snap, and the snap revision is more consistently updated, it is better to have that on issues than the output of `charm version`.
> Request snap info instead of charm version

- charmtools/build/builder.py
- charmtools/create.py
- charmtools/generators/generator.py
- tests/test_charm_create.py
Fixes #342 and partially addresses #327 by rejecting attempts to build or create into or from directories outside of `$HOME` with a clear error message.
> Validate that input and output paths can be accessed by snap

- charmtools/build/builder.py
- charmtools/generators/generator.py
- tests/generators/test_generator.py
- tests/test_charm_create.py
In the strictly confined snap, $HOME is set to the snap dir instead of the user's home dir.  Expanding ~user gets the correct path.
Fixes #348
> Fix home dir check in confined snap

- charmtools/build/builder.py
Config dir doesn't exist by default in the snap.
> Fix creation of config file

- charmtools/build/builder.py
Should be using HTTPS and `ev` field has to be an integer, so changed the fields around.
> Fix metrics request params

- setup.py
PyPI decided to not find the `README.rst` file, so quick fix.
> Fix README for PyPI being dumb

- Makefile
- charmtools/git_version.py
"Snap versions consist of upper- and lower-case alphanumeric characters, as well as periods, plus signs, tildes, and hyphens."
So, we now only use plus-signs, hyphens, and periods.
> Fix version chars and add pypi release make target

- charmtools/build/builder.py
- charmtools/generators/generator.py
- charmtools/utils.py
- tests/test_utils.py
Some build environments (i.e., Jenkins) don't set `$USER`, and in the snap, `$HOME` is set to something other than the user's home directory.  So we need to get the correct path in a way that doesn't rely on those env vars.
Fixes #367
> Don't rely on any env vars to determine $HOME

- MANIFEST.in
- charmtools/git_version.py
Use SNAPCRAFT_PROJECT_VERSION instead of SNAP_VERSION, as the latter is the version of the snapcraft snap instead of the charm-tools snap during build.
Use uncached SNAP_REVISION in charm-version because during build time it's the rev of the snapcraft snap doing the build and the charm-tools snap rev can't be known until after it's built and uploaded to the store.
Also fix the location of the VERSION file in the manifest.
> More version fixes

- charmtools/utils.py
- tests/test_utils.py
Addresses issues in #383 when the user isn't a proper full system uid
> Capture errors when user is not in /etc/passwd fixes #383

- charmtools/build/builder.py
- charmtools/create.py
- charmtools/generators/generator.py
- charmtools/proof.py
- charmtools/pullsource.py
- charmtools/utils.py
- tests/generators/test_generator.py
- tests/test_charm_create.py
Makes the home dir check non-fatal but follows it with a hard check for permissions, which is what we ultimately care about.  This allows for cases where we can't determine the home dir but the user is doing the right thing.
Fixes #383
> Improve error checking and reporting around home dir

- charmtools/bundles.py
- charmtools/charms.py
- charmtools/utils.py
- tests/test_bundle_proof.py
- tests/test_charm_proof.py
In order for correct presentation of charm names in the GUI and jujucharms.com this adds support for a `display-name` property. This will be used by charm authors to provide the correct spacing and casing for their charms ex) `PostgreSQL` instead of `postgresql`
> Add support for, and validation of display-name property

- charmtools/bundles.py
- charmtools/utils.py
- tests/test_bundle_proof.py
Allow `charm proof` to accept either `services` or `applications` in a bundle. Also fix up minor lint issues in utils and test_bundle_proof.
> allow applications key for charm proof (fixes #390)

- setup.py
Ensure that the version script is run with the same Python executable as the setup.py.  This fixes the snap build where there is a Python 2 executable on the path during install but we want to be using a specific Python 3 executable.
> Fix snap build

- .gitignore
- charmtools/build/tactics.py
In-progress support for handling series upgrade (e.g., trusty -> xenial)
> Add support for {pre,post}-series-upgrade hooks

- charmtools/build/tactics.py
Allow for the reactive library to have its own options section even though it's not a layer by itself.  We might want to support a more generic way of handling this, so that arbitrary libraries can defined
their own sections, perhaps via entry points, but this is a quick fix for the reactive library itself.
> Support charms.reactive layer options

- charmtools/build/fetchers.py
- tests/test_build.py
- tox.ini
To support layers and interfaces being nested inside larger repos instead of repos on their own, this adds support for a `subdir` field in the layer index.
Fixes #212
> Support subdir field in layer index

- charmtools/build/config.py
The builder uses ruamel rather than pyyaml, which uses a different exception.
Fixes #428
> Fix "no attribute parser" masking actual YAML parsing error

- charmtools/build/builder.py
- charmtools/git_version.py
- charmtools/version.py
- snap/snapcraft.yaml
- snap/workarounds/charmstore-client-version
Because the charmstore-client repo doesn't have official releases often, the base version number is often not indicative of what is actually included.  This extends the existing git_version support to include the charmstore-client component as well.
Example output:
```
charmstore-client 2.3.0+git-11-g5ea61cd
charm-tools 2.2.5+snap-x1+git-3-g32b98a2
```
> Report detailed version for charmstore-client

- HACKING.md
- charmtools/charms.py
- tests/test_charm_proof.py
made `charm-build` has the ability to parse `devices` metadata.
> made charm-build has the ability to parse devices metadata

- snap/snapcraft.yaml
It seems that snapcraft 2.43 introduced an issue with `snap pull $part; snapcraft` causing an "out of date" error.  This is supposed to work around that.
See https://bugs.launchpad.net/snapcraft/+bug/1791871
> Work around "out of date" error on LP builders

- snap/snapcraft.yaml
Not sure why this worked previously and no longer does, but without it the paths are still correct and it fixes the error.
> Remove source: key from snap to fix build

- charmtools/build/tactics.py
- helpers/snap-wrappers/charm
The version file was getting added to the manifest even if it wasn't created, causing a modification error stating that it was removed after the last build.
It was also failing if the charm was a git repo that didn't have annotated tags instead of just using the sha.
> Fix version causing build signature issues

- requirements.txt
- setup.py
- snap/snapcraft.yaml
Snap build failed with: Error:confinement 'classic' not allowed with plugs/slots.
> Remove plugs for classic snap

- charmtools/build/builder.py
- tests/test_build.py
- tests/trusty/b/metadata.yaml
Create relation hooks for all relations in metadata.yaml
Charms using relations without an external interface layer
now get relation hooks generated for them in the expected way,
and no longer need to maintain the hook stubs themselves.
Addresses #401 
My main use case for this are peer relations, of which there will only be a single implementation. It makes sense to development in the main charm's tree, but the hooks/*-relation-* files need to be manually maintained.
A number of tests needed mocks added, as they relied on plan_interfaces short circuiting when there were no interface: layers declared and skipping some sanity checks, and they had already mocked plan_hooks which durplicated those checks.
> Non interface relation hooks

- charmtools/build/tactics.py
This came up with the switch to classic confinement due to `.tox` directories getting picked up even though they were part of the ignore list.
> Fix interface layers linting ignored files

- snap/snapcraft.yaml
Rather than attempting to install wrappers in a scriptlet of an unrelated part, add a new part dedicated to properly installing the wrappers in the expected location.
> snapcraft.yaml: add new part for wrappers

- charmtools/build/builder.py
If the output dir for building doesn't exist, we should still succeed if we can read / write the parent directory, because the build path will be created on demand.                                          
Fixes #453
> Fix check_path failing on missing directory

- HACKING.md
- setup.py
During install, `setup.py` is called again and tries to pull the version info from git rather than using the prepared cached `VERSION` file.
Fixes #457
> Fix version in setup.py during install

- charmtools/build/builder.py
- charmtools/build/fetchers.py
- snap/snapcraft.yaml
The requests library doesn't support `file://` URLs, so we have to handle them specially.  This allows for a copy of the layer-index repo to be cloned locally and used instead.
Also rename `--interface-service` to `--layer-index`, partially addressing #438.
> Add support for local layer-index

- charmtools/build/builder.py
- setup.py
The implicit default of None for `--interface-service` was somehow overwriting the actual default for `--layer-index`.
Also fix the security complaint from GitHub with the older Paramiko version.
> Fix default value for --layer-index option

- charmtools/build/builder.py
- charmtools/build/fetchers.py
- charmtools/build/inspector.py
- charmtools/fetchers.py
This allows tracking of exactly what a given charm was built with.
The build manifest is now (as of the latest charm snap release) uploaded to the store.
This doesn't provide any way of using this info to manage a rebuild, but it can at least be done manually via local checkouts of the layers, if needed.
Fixes #403
> Add revision info to build manifest

- charmtools/build/builder.py
This patch address issue #442, where a failed charm proof does not
return a non-error exit code for `charm build`.
> Fix issue 442 - raise error if proof fails

- README.rst
- charmtools/build/builder.py
- charmtools/build/fetchers.py
Previous to #478, the behavior of `--output-dir` matched that of `$JUJU_REPOSITORY` in that it specified a directory which would have a `builds` or `{series}` directory created under it, which would then have the final charm output dir created under that.  This got changed and broke the charm builds for OpenStack, so this restores the previous behavior of `--output-dir` while retaining the new semantics for `--build-dir`.
> Restore historical behavior for --output-dir

- charmtools/build/builder.py
This commit fix the typo of the previous commit (5807aa1d) so we could
retain the alias of `--build-dir` when using `--output-dir`.
- The link does not work anymore. Both of the links are empty as well https://github.com/juju-solutions/hacking.juju.solutions and https://github.com/juju-solutions/hacking-guide
> Fix typo to make the argument alias keep working

- charmtools/build/fetchers.py
- tests/test_build.py
In https://review.openstack.org/#/c/635686/ I got:
```
OSError: [Errno 39] Directory not empty
```
I'm not sure if that was a spurious error because we haven't hit it before, but `shutil.copytree` is better suited for this anyway.
> Use shutil.copytree instead of path.rename

- charmtools/build/config.py
By default, the `charm build` command excludes any file or folder with
the name `build`. It might be necessary to have such folder's name in the
charm.
It fixes #485 
Dead link
> Allow `build` folders in the charm

- charmtools/build/builder.py
- charmtools/build/inspector.py
The `charm layers` command was broken with the addition of revisions to the manifest.  This fixes that, and also adds some additional functionality, such as the ability to annotate the source layer when colors aren't available, and a larger number of colors to choose from so that charms with many layers won't run out quite as soon.
> Fix and improve charm-layers

- charmtools/build/builder.py
`os.path.commonpath` was added in 3.5
> Fix nested build dir check in Python2

- snap/snapcraft.yaml
```
Building charmstore-client 
Collecting vergit
[11/Mar/2019:19:11:03 +0000] "CONNECT pypi.python.org:443 HTTP/1.0" 200 4784 "-" "-"
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Downloading https://files.pythonhosted.org/packages/d8/dc/2ef077a97a05633bbe7a46b9cb4b87fbf994a9aaa52b44a8f1086d20951f/vergit-1.0.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named setuptools
```
> Ensure setuptools for charmstore-client build

- charmtools/build/builder.py
- charmtools/build/fetchers.py
- charmtools/fetchers.py
- charmtools/pullsource.py
- tests/test_build.py
Adds support for `--layer-index` and `--fallback-layer-index` option to `charm pull-source` and the support for the latter to `charm build` as well.
Also fix an infinite recursion bug when dealing with local interface layers, due to an incorrect `super()` call.
> Add support for layer-index to pull-source and multiple indexes

- charmtools/build/fetchers.py
If the layer index contains invalid JSON, it can cause the build to fail with a stack trace rather than a useful error message.
> Gracefully handle JSON decode errors from layer index

- setup.py
The vergit package is used to calculate the version number from the git history and tags.  It was not supposed to be required during installation, but it was not handled properly when missing.
Fixes #518
> Fix installation dependency on vergit

- setup.py
Another corner case is installing directly from git but without vergit available, in which case there's no way to determine the version and we have to fall back to `None` (a.k.a. `0.0.0`).
Fixes #518
> Fix installing from git without vergit installed

- .travis.yml
- tox.ini
Relates to https://github.com/Homebrew/homebrew-core/pull/40496
Trying to upgrade to use Python 3.7 (which travis has the support with `dist: xenial`).
> Upgrade to use py3.7

- charmtools/build/builder.py
- charmtools/utils.py
Some paths that are excluded by default (such as `.tox` env dirs) may still end up in the built charm from post-build steps (such as running tests against the built charm). The builder should not complain about those paths when rebuilding.
Fixes #528
> Honor ignores / excludes when checking for added files

- charmtools/charms.py
Fixes #533
Adjust the config item key regexp check to allow one and two character config.yaml keys.
> Fix config key regexp to allow short config keys.

- requirements.txt
As a common used python utils, limit `requests` to old version will
conflict with plenty of other packages.
For example, it breaks `tox -e pep8` test in `charm-keystone`,
as reported in #535 and https://bugs.launchpad.net/charm-keystone/+bug/1836119
Adjust version limit to 2.0.0 <= version < 3.0.0
Closes #535 
- [N] Have you followed [Juju Solutions hacking guide?](https://hacking.juju.solutions) --> URL is dead
- [Y] Are all your commits [logically] grouped and squashed appropriately?
- [Y] Does this patch have code coverage?
- [Y] Does your code pass `make test`?
> requirements.txt: update version limit for requests (#535)

- tox.ini
Newer versions of tox restrict access to commands unless you explicitly whitelist or install them.
> Update pypi release target to work with newer tox

- .github/PULL_REQUEST_TEMPLATE.md
The URL in the PR template never existed and shouldn't have been included.
Fixes #245
> Remove bad URL from PR template

- charmtools/version.py
There's an edge case that leads to `charm version` failing like this:
```bash
$ charm version
Traceback (most recent call last):
File "/usr/local/bin/charm-version", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/charmtools/version.py", line 95, in main
format_version(cached_charmstore_client_version(), args.format)))
File "/usr/local/lib/python3.5/dist-packages/charmtools/version.py", line 56, in cached_charmstore_client_version
return _add_snap_rev({'version': charm_ver})
UnboundLocalError: local variable 'charm_ver' referenced before assignment
```
It happens when `charm` is not installed via apt nor snap, but rather with `go get` as described in [the docs](https://github.com/juju/charmstore-client#charmstore-client). In this case, our apt cache will …
> edge case for setting charm_ver

- charmtools/build/builder.py
- charmtools/build/fetchers.py
- charmtools/build/tactics.py
- charmtools/utils.py
- snap/hooks/post-refresh
- snap/snapcraft.yaml
The build process currently leaves directories under `~/.cache/charm/{layer,interface}/` which over time can build up and waste space.
Fixes #539
Additionally:
* Fix handling of excludes in interface layers. The `ignore` setting is honored by interface layers but actually uses the mechanic of `exclude`, while `exclude` itself is not honored. This adds support for `exclude` with the proper behavior and leaves `ignore` as-is for compatibility.
* Improve error reporting during interface layer linting when a file fails to decode.
* Fix a snapcraft error if python binary already exists.
> Cleanup cached layers / interfaces after build

- charmtools/build/builder.py
`charm build --help`:
Build charms will be placed into $CHARM_BUILD_DIR/{charm_name} (defaults to current directory)
This is not true, the real path in code is `/tmp/charm-builds/`
Signed-off-by: Joe Guo <guoqiao@gmail.com>
> fix charm build help message

- charm.1
Moves the the bug reporting URL to match HACKING.md and
updates the copyright notice to be more recent than 2011.
> Update charm.1 manpage

- charmtools/build/builder.py
- charmtools/charms.py
Include PID in cache dir so that concurrent builds will not collide.
Fixes #487
Fixes #517
Fixes #541
> Fix charm-build conflict when building concurrently

- snap/snapcraft.yaml
Snap builds for several arches have been failing for a long time due to the setuptools / pip `__legacy__` attribute issue.  This fixes that by removing unnecessary system packages during the build.
Fixes #521 
Tested with `snapcraft remote-build --arch armhf`
> Fix snap builds on other arches

- charmtools/charms.py
- tests/layers/tester/metadata.yaml
- tests/test_build.py
The maintainer email validation code used [`email.utils.parseaddr`](https://docs.python.org/3/library/email.utils.html#email.utils.parseaddr) but then second-guessed it by reformatting it and trying to do manual parsing, which failed with non-ASCII characters.
Fixes #531
> Fix maintainer validation not handling unicode

- charmtools/fetchers.py
- tests/test_fetchers.py
Related to #552
https://bugs.launchpad.net/charm-barbican/+bug/1846263
> Add opendev.org https and git fetcher

- charmtools/charms.py
- tests/test_charm_proof.py
It is occasionally useful to have an explicit null / None default value for boolean config options to detect the difference between the user explicitly wanting false or not. This changes the proof message to informational.
> Allow boolean config options to have null default

- requirements.txt
This change supports use of the OpenStack charm create templates
as part of the charm snap.
> Add OpenStack templates to requirements

- snap/snapcraft.yaml
On environments with user site packages installed, they can be picked up by the Python bundled into the snap and cause version conflicts. This workaround [borrowed from snapcraft](https://github.com/snapcore/snapcraft/blob/bd5be51/tools/snapcraft-override-build.sh#L18) prevents this.
Fixes #559
> Add workaround for user site package conflicts

- .github/workflows/build-snap.yml
* Rename output artifact to `charm.snap`; this will download as `charm.snap.zip` which will need to be unzipped to get the actual snap
* Rename yaml file so we can add other actions in the future.
> Tweak Build Snap action

- charmtools/build/config.py
This commit addresses the concerns raised in issue #421 with charm proof
failing on vim swap files when someone has a readme file open in an
editor while running charm build which then compiles and proofs the
README*.swp file which is not UTF-8 compliant.
- [] Does your code pass `make test`?
- Having trouble with python dependencies for test.
> Add vim *.swp files to DEFAULT_IGNORES

- charmtools/templates/operator_python/template.py
Changes the default bug tracker URL to a location that actually exists.
> Default to charming category of the Juju Discourse

- charmtools/build/builder.py
Fixes spurious build errors like:
```python-traceback
Traceback (most recent call last):
File "/snap/charm/461/bin/charm-build", line 11, in <module>
load_entry_point('charm-tools==2.7.4', 'console_scripts', 'charm-build')()
File "/snap/charm/461/lib/python3.6/site-packages/charmtools/build/builder.py", line 941, in main
build()
File "/snap/charm/461/lib/python3.6/site-packages/charmtools/build/builder.py", line 649, in __call__
self.generate()
File "/snap/charm/461/lib/python3.6/site-packages/charmtools/build/builder.py", line 592, in generate
layers = self.fetch()
File "/snap/charm/461/lib/python3.6/site-packages/charmtools/build/builder.py", line 272, in fetch
self.post_metrics('charm', self.name, False)
File "/snap/charm/461/lib/python3.6/site-packages/charmtools/build/builder.py", …
```
> Handle invalid config file more gracefully

- charmtools/build/builder.py
- charmtools/build/tactics.py
- tests/test_build.py
Processing the wheelhouse.txt file from each layer in isolation means that pip can't resolve conflicts, duplicates, or dependency version pinning which spans across layers.  This can lead to duplicate versions of libraries being installed which violate constraints to avoid certain upstream bugs.
This came up in both of:
* https://bugs.launchpad.net/charm-flannel/+bug/1884598
* https://bugs.launchpad.net/charm-octavia/+bug/1884164
And in both cases trying to resolve it on a per-layer or per-charm basis results in a whack-a-mole process of catching all of the layers which indirectly reintroduce the unpinned version of a 
dependency pinned in a base layer.
> Process wheelhouse.txt holistically rather than per-layer

- charmtools/build/tactics.py
- tests/layers/whbase/wheelhouse.txt
- tests/test_build.py
- tests/wh-over.txt
Ensure that matches are made even if packages use different conventions (hyphens vs dashes) by using `pkg_resources.safe_name()` to normalize the package names using standard tools.
Fixes #575
> Normalize package names when processing wheelhouse

- charmtools/build/fetchers.py
- charmtools/fetchers.py
- charmtools/pullsource.py
- requirements.txt
- tox.ini
Adds the ability to specify a branch to switch to when fetching the source of a charm or layer.  This is particularly useful for layer
entries which use the `subdir` field, since that can lose the SCM metadata and prevent post-pull switching.
Fixes #580
Fixes [lp:1893081](https://bugs.launchpad.net/charmed-kubernetes-testing/+bug/1893081)
> Add --branch option to pull-source

- charmtools/build/config.py
- charmtools/fetchers.py
- charmtools/pullsource.py
In addition to displaying the rev when using pull-source on a layer which uses the subdir field, we need to store it on disk for charm-build to use later in the build manifest.
Fixes [lp:1894331](https://bugs.launchpad.net/charmed-kubernetes-testing/+bug/1894331)
> Store rev when pull-source on a subdir layer

- charmtools/charms.py
Because YAML can end up treating a bare X.Y number as a float rather than a string, the linter was blowing up with an exception
(`TypeError: expected string or bytes-like object`) instead of a useful error about the format of the min-juju-version field.
Drive-by: Update to match [current regexp from upstream][regexp].
[regexp]: https://github.com/juju/version/blob/d414598/version.go#L108
> Fix TypeError from linter on X.Y min-juju-version

- setup.py
keyring 21 depends on secretstorage>=3.2, so if we pin
secretstorage<2.4 we also must pin keyring<21. This is
what we do in requirements.txt already so this commit
is just aligning setup.py.
> Align setup.py to requirements.txt

- charmtools/promulgation.py
Minor issue in the code for reporting the error case where you try to promulgate a charm where one is already promgulated from another namespace. Also improve the error message to indicate the correct action to take.
> Fix exception rendering "already promulgated" error

- charmtools/build/__init__.py
- charmtools/build/builder.py
- charmtools/build/fetchers.py
- charmtools/build/tactics.py
- charmtools/fetchers.py
- docs/index.rst
- docs/reproducible-charms.rst
- requirements.txt
- tests/test_build.py
This feature adds some command line options to allow the generation of
the build.lock file in the top layer.  This can then be used to rebuild
the charm with the exact same set of layers and python modules. Also the
ability to track a specific branch is also enabled.
> Add reproducible charm build feature

- charmtools/charms.py
- tests/test_charm_proof.py
Add 'docs' to known metadata fields and warn rather than error on unknown fields in preparation for metadata v2
> Add 'docs' to known metadata fields

- charmtools/build/builder.py
- charmtools/build/config.py
- tests/test_build.py
The new pattern used by `charmcraft` is to create a file named `{charm-name}.charm` in the current directory, which is a zip archive of the charm. This adds a `--charm-file` (`-F`) option to also create that file in the same way.
> Add option to create .charm file

- charmtools/build/builder.py
- charmtools/build/config.py
- charmtools/build/fetchers.py
The issues fixed in this are:
* --ignore-lock-file didn't fully ignore the lock file.
* rebuilding resulted in missing libraries due to purging the wheels.
Purging was not needed.
* The wrong fetcher classes were used when rebuilding from lock-files.
This had the side-effect of not being able to handle multi-layer git
repositories.  This has been resolved.
* Fix hard-coded WheelhouseTactic in builder.py
When doing either the reproducible charms or the wheelhouse overrides,
the builder used to use the WheelhouseTactic directly.  This breaks any
code that might override the WheelhouseTactic.  Instead, if an existing
wheelhouse tactic is in use, use that one's class; if it's not, then
default back to the base WheelhouseTactic.  May help with bug #585
* Fix test problems with missing …
> Fix reproducible charms issues

- charmtools/charms.py
- tests/test_charm_proof.py
The charmcraft is using bases in charmcraft.yaml instead of series in
metadata.yaml, so the series should not be used anymore.
fixes: #615 
> Add warning message if series is in metadata.yaml

- charmtools/build/builder.py
- charmtools/build/tactics.py
The reactive framework was born in a time of the now legacy charm store.  The legacy charm store did not have awareness for binary compatibility with various CPU architectures.
In order to enable the use of Python virtual environments, and at the same time support multiple CPU architectures, the charm-tools build action currently uses `pip download` to retrieve the source code of Python dependencies.  On charm install layer-basic will subsequently use pip to build and install the dependencies on the target.
Over the recent years this approach has become increasingly difficult to maintain.  The Python ecosystem has a plethora of build automation and package mangement projects, and each and every Python dependency makes their own choices about what to use.
Adding to that, pip does not …
> Add option to build charm with binary wheels

- charmtools/pullsource.py
- tests/test_pullsource.py
* Adds unit test coverage for pull sources
* Provides reasoning as to why a fetch error has occurred
> add unit test coverage for pull-sources

- helpers/snap-wrappers/charm
> snap: Fix GIT_TEMPLATE_DIR environment variable

- charmtools/build/tactics.py
At present we call out to Python provided by the build environment to create a correct wheelhouse.
However, we are not pruning GIT related environment variables set by the snap.  This in turn makes git clone fail when the `git` binary from the build environment attempts to use git resources in the snap, which may be of a different version.
Fixes #632
> Prune GIT environment variables when using Python from buildenv

- charmtools/version.py
Due to how some other projects parse our version string the current format may break people.
Fixes #636
> Fix version output to be compatbile with sibling projects

- charmtools/build/builder.py
When running 'apt' within the snap the environment variables set will make it run with the python version embedded in the snap instead of the system's tools, this will make the package installation fail with the following error:
Setting up python3-pkg-resources (45.2.0-1) ...
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
File "/snap/charm/677/usr/lib/python3.10/io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
dpkg: error processing package python3-pkg-resources (--configure):
installed python3-pkg-resources package post-installation script subprocess returned error exit status 1
Test case:
git clone …
> Clear environment variables when running apt

- .github/workflows/tests.yml
- charmtools/build/builder.py
- charmtools/build/tactics.py
- charmtools/utils.py
- tests/test_utils.py
Some packages may require newer versions of core dependencies for successful execution of the `pip download` or `pip wheel` commands. Most notable example is Jinja2 and MarkupSafe when installed on Focal ref pallets/jinja#1496.
At this stage of the process the input from the charm wheelhouse.txt is not sufficient.
Add an option to upgrade pip and setuptools in the build venv to deal with these situations.
Fixes: #646
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
> Add option to upgrade core deps in build venv

- setup.py
- tests/test_build.py
- tests/wh-over.txt
A change in the strictness of how pip requirements lines are parsed means that the lib needs a tactical fix to enable testing to move forwards.  A more complete fix is to remove the upper bounds and the main development branch.
> Fix a couple of pip requirement lines

- charmtools/build/tactics.py
- charmtools/utils.py
- tests/test_utils.py
PEP-440 is more strict about requirement lines.  As an example:
pytz>dev
is non-compliant, but is in 5.2.4 of kombu's requirements.  This breaks building wheelhouses from source (such as the octavia charm).  This patch pins pip and setuptools to the latest versions that will defintely still allow PEP-440 non-compliant packages to install.
The option --upgrade-buildvenv-core-deps can be used to override this and will install the latest versions of pip and setuptools available.
Fixes-Bug: #652
> Pin pip<23.1 and setuptools<67 to allow PEP-440 non compliance

- .github/workflows/tests.yml
- setup.py
pyyaml 5.4.0 and 5.4.1 are broken with cython 3
https://github.com/yaml/pyyaml/issues/724
jsonschema 4.18.0 depends on Rust (via rpds-py)
> setup: Update charm-tools pin set

- setup.py
Allow the use of PyYAML 6.x with the exception of PyYAML-6.0 which has a broken build dependency relation to Cython.
This allows migrating away from PyYAML-5.3.1 which has known security bugs[0]
[0] https://security.snyk.io/package/pip/PyYAML/5.3.1
> setup: Update pin PyYAML

- charmtools/build/__init__.py
- charmtools/build/builder.py
- charmtools/build/tactics.py
- charmtools/bundles.py
- charmtools/charms.py
- charmtools/generators/utils.py
- charmtools/proof.py
- charmtools/test.py
- charmtools/utils.py
- docs/_extensions/automembersummary.py
- docs/conf.py
- setup.cfg
* `lint` target: this ignores the vendored in
`charmtools/diff_match_patch.py` file which uses completely
non-standard indenting (2 spaces). It also fixes various issues around
bare exceptions, indendation and equality tests on types.
* `docs` target: this fixes the custom
/docs/_extensions/automembersummary.py extension to be able to use a
more recent version of sphinx. This fixes a long-standing broken
sphinx docs generation issue.
> Fix issues with tox targets lint & docs

- charmtools/build/__init__.py
- charmtools/build/builder.py
- charmtools/bundles.py
- charmtools/charms.py
- charmtools/generators/utils.py
- charmtools/proof.py
- charmtools/test.py
- charmtools/utils.py
- charmtools/version.py
- docs/_extensions/automembersummary.py
- docs/conf.py
- setup.cfg
* `lint` target: this ignores the vendored in
`charmtools/diff_match_patch.py` file which uses completely
non-standard indenting (2 spaces). It also fixes various issues around
bare exceptions, indendation and equality tests on types.
* `docs` target: this fixes the custom
/docs/_extensions/automembersummary.py extension to be able to use a
more recent version of sphinx. This fixes a long-standing broken
sphinx docs generation issue.
(cherry-picked from b7e51d5cf93070762215ebec06bb13e471d6511c)
(charmtools/build/tactics.py needed revisions to pick.)
> [2.8] Fix issues with tox targets lint & docs

- snap/snapcraft.yaml
setuptools-scm depends on setuptools>=61, while the one installed in the building environment is setuptools-59.x which comes from the deb package available in Ubuntu-22.04.
This change upgrades setuptools to allow the building to succeed. Also uses an absolute path when running `vergit` to fix a "command not found" error.
Fixes #666
- [] Does this patch have code coverage?
- [] Does your code pass `make test`?
> Upgrade setuptools

- setup.py
ruamel.yaml 0.18 hard deprecated the old PyYAML functions removing
yaml.safe_load among many others. This causes charm-build to exit
sometimes without a visible error.
Fixes: #668
Reference: https://pypi.org/project/ruamel.yaml/0.18.0/
> setup: pin ruamel.yaml to <0.18

- snap/snapcraft.yaml
the bhttp snap is available in latest/edge for the architectures we care
about. This enables the building of charm-tools as a snap in non-amd64
architectures.
Closes #666
> Use bhttp from latest/edge

- setup.py
macaroonbakery in v1.3.4 added a constraint of protobuf>=3.20.0[0] which makes it incompatible with python 3.6 and v1.3.3 was released in a broken state[1].
> setup: pin macaroonbakery<1.3.3 for python3.6

- .github/workflows/tests.yml
- charmtools/build/tactics.py
- charmtools/utils.py
- setup.py
- tests/test_build.py
- tests/test_utils.py
- tox.ini
This PR adds support for Python 3.12, summary of changes:
* Add Python 3.12 to the testing matrix in the github workflow
* Replace `inspect.getargspec()` with `inspect.getfullargspec()`
* Replace `self.assertEquals()` with `self.assertEqual()`
* Add charmcraft 3.x/beta to the testing matrix
* Drop charm-templates-openstack from deps
* setup.py: Drop upper limit in pinning of pip
> Python 3.12 support

- setup.py
With `path==17.0.0`, some methods have been deprecated which were in use by this project
Since `path.py` was just a direct install of `path` with no restrictions, lets just remove `path.py` and pin `path`
https://github.com/jaraco/path/commit/7e23a1d7a5fc6412926e6e72be00e5479e86fec4
> Pin the version of path since 17.0 removed deprecated methods

- .github/workflows/tests.yml
- snap/snapcraft.yaml
When building the snap on s390x some Python modules need to compile their extensions (rust based), this is not needed on amd64 since pypi has compiled packages available.
This change add rustc, cargo and pkg-config to the list of build-packages in the snapcraft.yaml definition.
> snap: Add rust to build-packages

- .github/workflows/build-snap.yml
- snap/snapcraft.yaml
When building the snap on s390x some Python modules need to compile
their extensions (rust based), this is not needed on amd64 since pypi
has compiled packages available.
This change add rustc, cargo and pkg-config to the list of
build-packages in the snapcraft.yaml definition.
* Migrate gh action actions/upload-artifact@v4
* Migration gh action actions/download-artifact@v4
The backport was adjusted to use build-snap.yml workflow instead of
test.yml
(cherry picked from commit b8747e01d3bcbc50504c6cf5e553843e13ae9f94)
> snap: Add rust to build-packages [2.8 backport]

- .github/workflows/tests.yml
- charmtools/build/builder.py
- charmtools/build/tactics.py
- charmtools/version.py
- setup.py
- snap/snapcraft.yaml
This new flag allows to instruct pip to ignore if the Python version is
explicitly supported by the package.
This flag is helpful to build old charms that are using a src/build.lock
where the package doesn't explicitly states support, this was detected
in charm-octavia[0]
[0] https://review.opendev.org/c/openstack/charm-octavia/+/962501/1#message-7dd7c13d1ef1ff20312e63f105c362aa8e9bf5c1
> Add --ignore-requires-python
